# Generated by Django 4.2 on 2026-09-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='password',
            field=models.CharField(max_length=135),
        ),
    ]
